spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    database: postgresql
  flyway:
    enabled: true
    default-schema: public
    baseline-on-migrate: true
    clean-disabled: true
    schemas: [ public ]